server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: system log
      __path__: /var/sys_log/*log
- job_name: app
  static_configs:
  - targets:
      - localhost
    labels:
      job: app log
      __path__: /var/app_log/*log
