name: Build Docker Image and Push

on:
    [workflow_dispatch]

jobs:
       build:
        runs-on: nginx:alpine

        steps:
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Build & push Docker image
            uses: mr-smithers-excellent/docker-build-push@v6
            with:
              image: itsbijaya/real-hr
              tags: latest
              registry: docker.io
              dockerfile: Dockerfile
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
