name: Build Docker Image and Push

on:
    
  push: 
    branches: ['main']

  workflow_dispatch:



jobs:
       build:
        runs-on: ubuntu-latest

        steps:
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '20'

          - name: Install dependencies
            run: npm install

          - name: Build Vitepress
            run: npm run docs:build

          - name: Build & push Docker image
            uses: mr-smithers-excellent/docker-build-push@v6
            with:
              image: itsbijaya/real-hr
              tags: latest
              registry: docker.io
              dockerfile: Dockerfile
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSHKEY }}
              known_hosts: ${{ secrets.HOST }}
              if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          - name: whoami
            run: whoami

            
          - name: Deploy to remote server
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSHKEY }}
              script: |
                 # ... (rest of your script)
                  timeout: 300  # Increase timeout to 5 minutes
                  debug= true
          - name: Test SSH connectivity
            run: ssh -o StrictHostKeyChecking=no ${SECRETS.USERNAME}@${{ secrets.HOST }}