name: Build Docker Image and Push

on:
  push: 
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vitepress
        run: npm run docs:build

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: itsbijaya/real-hr
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}  # The private SSH key stored in GitHub Secrets
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }} # Store the known_hosts in GitHub Secrets to avoid SSH host verification issues
          config: ${{ secrets.CONFIG }} # SSH config if needed
          if_key_exists: fail

      - name: Rsync over SSH
        run: rsync -r ./foo/ user@remote:/bar/ # Replace 'foo' and 'bar' with your paths

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}  # Remote server IP or hostname
          username: ${{ secrets.USERNAME }} # Remote server username
          key: ${{ secrets.SSHKEY }} # Private SSH key for authentication
          port: ${{ secrets.PORT }} # SSH port (default is 22)
          script: whoami
      

